### ISSUE TITLE
Call to undefined when scanning SSLv2

### ISSUE THREAD

**Issue by carwyn** [ThreatLabsNL/TLScan#4]
When scanning a host with SSLv2 enabled (scanning for DROWN as it happens):

```
Traceback (most recent call last):
  File "./TLScan.py", line 838, in <module>
    main()
  File "./TLScan.py", line 817, in main
    processTarget(target)
  File "./TLScan.py", line 775, in processTarget
    supportedCiphers = enumCiphers(p)
  File "./TLScan.py", line 713, in enumCiphers
    for cipher in chunks(cipher_spec, 3):
NameError: global name 'chunks' is not defined
```

**Comment by mjol** [comment]
The function was indeed missing in the file, find it in the latest version
